# DB_URL="jdbc:postgresql://db.ylqbajpmlqptblhjgnva.supabase.co:5432/postgres" 
# DB_USERNAME="postgres" 
# DB_PASSWORD="VqhtpZxIvIch7dUr" 
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres.ylqbajpmlqptblhjgnva}
spring.datasource.password=${DB_PASSWORD:VqhtpZxIvIch7dUr}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# VqhtpZxIvIch7dUr