# DB_URL="jdbc:postgresql://db.ylqbajpmlqptblhjgnva.supabase.co:5432/postgres" 
# DB_USERNAME="postgres" 
# DB_PASSWORD="VqhtpZxIvIch7dUr" 
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres.ylqbajpmlqptblhjgnva}
spring.datasource.password=${DB_PASSWORD:VqhtpZxIvIch7dUr}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# VqhtpZxIvIch7dUr

jwt.secret=3f2a1b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect